server:
  port: 8761
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
    registerWithEureka: false
    fetchRegistry: false
management:
  endpoints:
    web:
      exposure:
        include=*: