spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/${DATABASE_NAME:dental-clinic}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:admin}
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
  jpa:
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA:locationservice}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
  instance:
    preferIpAddress: true

springdoc:
  cache:
    disabled: true
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: dental-service
      authorizationUrl: https://${AUTH_SERVER_HOST:auth-service}:${AUTH_SERVER_PORT:8443}/realms/dental-client/protocol/openid-connect/auth
      tokenUrl: https://${AUTH_SERVER_HOST:auth-service}:${AUTH_SERVER_PORT:8443}/realms/dental-client/protocol/openid-connect/token
management:
  endpoints:
    web:
      exposure:
        include=*: