version: "3.8"
volumes:
  postgres_data:
    driver: local
networks:
  local:
    driver: bridge
services:
  postgres:
    image: postgres:16
    container_name: db
    volumes:
      - ./db/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dental-clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - local
  dental-service-keycloak:
    image: custom-keycloak
    container_name: auth-service
    build:
      context: ./
      dockerfile: ./auth-service/Dockerfile
    deploy:
      replicas: 1
#    command: ["-Djboss.http.port=8443"]
    hostname: auth-service
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - local
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: dental-clinic
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_HOSTNAME: auth-service
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/auth-service.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/auth-service.key.pem
      KC_HTTPS_KEY_STORE_PASSWORD: Zaq12wsx

  dental-service-config:
    image: adamn2000/config-service:latest
    container_name: config
    networks:
      - local
    environment:
      CONFIG_PORT: 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
  dental-service-discovery:
    image: adamn2000/discovery-service:latest
    container_name: discovery
    networks:
      - local
    depends_on:
      dental-service-config:
        condition: service_healthy
    environment:
      CONFIG_SERVER_HOST: dental-service-config
      CONFIG_SERVER_PORT: 8080
      EUREKA_SERVER: dental-service-discovery
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
  dental-service-gateway:
    image: adamn2000/gateway-service:latest
    container_name: gateway
    networks:
      - local
    depends_on:
      dental-service-config:
        condition: service_healthy
      dental-service-discovery:
        condition: service_healthy
    environment:
      CONFIG_SERVER_HOST: dental-service-config
      CONFIG_SERVER_PORT: 8080
      EUREKA_SERVER: dental-service-discovery
      OPENAPI_HOST: dental-service-gateway
      AUTH_SERVER_HOST: auth-service
      AUTH_SERVER_PORT: 8443
    ports:
      - "8080:8080"
  dental-service-location:
    image: adamn2000/location-service:latest
    container_name: location
    networks:
      - local
    depends_on:
      dental-service-config:
        condition: service_healthy
      dental-service-discovery:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      PORT: 8080
      CONFIG_SERVER_HOST: dental-service-config
      CONFIG_SERVER_PORT: 8080
      EUREKA_SERVER: dental-service-discovery
      AUTH_SERVER_HOST: auth-service
      AUTH_SERVER_PORT: 8443
      DATABASE_HOST: postgres
      DATABASE_NAME: dental-clinic
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_SCHEMA: locationservice
  dental-service-user:
    image: adamn2000/user-service:latest
    container_name: user
    networks:
      - local
    depends_on:
      dental-service-config:
        condition: service_healthy
      dental-service-discovery:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      PORT: 8080
      CONFIG_SERVER_HOST: dental-service-config
      CONFIG_SERVER_PORT: 8080
      EUREKA_SERVER: dental-service-discovery
      AUTH_SERVER_HOST: auth-service
      AUTH_SERVER_PORT: 8443
      DATABASE_HOST: postgres
      DATABASE_NAME: dental-clinic
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_SCHEMA: userservice
  dental-service-reservation:
    image: adamn2000/reservation-service:latest
    container_name: reservation
    networks:
      - local
    depends_on:
      dental-service-config:
        condition: service_healthy
      dental-service-discovery:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      PORT: 8080
      CONFIG_SERVER_HOST: dental-service-config
      CONFIG_SERVER_PORT: 8080
      EUREKA_SERVER: dental-service-discovery
      AUTH_SERVER_HOST: auth-service
      AUTH_SERVER_PORT: 8443
      DATABASE_HOST: postgres
      DATABASE_NAME: dental-clinic
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_SCHEMA: reservationservice