version: "3"
volumes:
  postgres_data:
    driver: local
networks:
  local:
    driver: bridge
services:
  postgres:
    image: postgres:16
    container_name: db
    volumes:
      - ./db/init-auth-server-schema.sql:/docker-entrypoint-initdb.d/init-auth-server-schema.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dental-clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - local
  dental-service-keycloak:
    extends:
      file: ./auth-server/docker-compose.yml
      service: auth-server
    depends_on:
      - postgres
    networks:
      - local
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: dental-clinic
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin