version: "3"
volumes:
  postgres_data:
    driver: local
networks:
  local:
    driver: bridge
services:
  postgres:
    image: postgres:16
    container_name: db
    volumes:
      - ./auth-server/db/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dental-clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - local
  dental-service-keycloak:
    image: custom-keycloak
    container_name: auth-server
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    ports:
      - "8181:8080"
    networks:
      - local
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: dental-clinic
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin