spring:
  application:
    name: gateway-service
  config:
    import:
     - "configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8088}"
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:dental-service.p12
    key-store-password: Zaq12wsx
    key-alias: dental-service