spring:
  application:
    name: user-service
  config:
    import: "configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8088}"
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20

openApiConfig: "production"