spring:
  application:
    name: user-service
  config:
    import: "configserver:${CONFIG_SERVER:http://localhost:8088}"
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20